development:
  host: 127.0.0.1
  subscriptions:
    talkyoo.numberman2
  publishing_queue:
    talkyoo.numberman2

production:
  host: 127.0.0.1
  subscriptions:
     foo
     bar
  publishing_queue:
    sample_project

